### ISSUE TITLE
Using custom cell-line data

### ISSUE THREAD

**Issue by sion100482** [broadinstitute/depmap_omics#119]
Hi,
First, I am attempting to run copynumbers.py. However, the error message "No module named 'gumbo_client'" appeared. So I did 'pip install gumbo_client', but I got an error message saying "No matching distribution found for gumbo_client", so I can't find a way. How can I solve it?

Second, using this pipeline, I want to obtain copy number alteration from my cell-line WES data. How can I do it?

Thank you.

**Comment by qinqian** [comment]
Hi,
Sorry for the late reply, `gumbo_client` is an internal tool for DepMap only. We will plan to separate internal tool in the future, but that takes a long time to accomplish. Thank you!
Best
