### ISSUE TITLE
New cell lines in 23q2 release not at Cellosaurus (no RRID)

### ISSUE THREAD

**Issue by mjsteinbaugh** [broadinstitute/depmap_omics#158]
Hi DepMap team,

I noticed that there are 5 new cell lines in the DepMap 23q2 release that are not annotated at Cellosaurus currently. Can we work on adding them? Happy to help if possible.

```
DepMap ID   Name    Source
ACH-001134  MYLA    Academic lab
ACH-001172  U251MGDM    HSRRB via Bandhyopadhyay (Broad)
ACH-002002  A375SKINCJ2 Cory Johannessen (Broad)
ACH-002471  PSS008  Alejandro Sweet-Cordero (UCSF)
ACH-002834  PSS131R Alejandro Sweet-Cordero (UCSF)
```

See related issue filed with the Cellosaurus team https://github.com/calipho-sib/cellosaurus/issues/8

Best,
Mike

**Comment by 5im1z** [comment]
Hi Mike,

Thanks for pointing this out! Looking at the other issue you linked, seems like the lines remaining to resolve are MYLA and U251MGDM. Regarding MYLA - do you happen to know what information would be helpful in determining origin? As for U251MGDM, based on our analysis, this line is a U251MG (ACH-000232) derivative and not initially derived from R262 or R256 as originally though. Therefore, it may necessitate its own Cellosaurus ID but we will let Amos decide.

Best,
Simone
