### ISSUE TITLE
Are we able to download latest data showed in website from this site? 

### ISSUE THREAD

**Issue by AR-Shicheng** [broadinstitute/depmap_omics#196]
Dear Team, 

Are we able to download latest data showed in website from this site? Since the website data is required to download by button and click operation. 

Looking forward to having some command line based approach to download the data. 

Thanks. 

Shicheng

**Comment by 5im1z** [comment]
Hi Shicheng,

Please refer to the latest comment in [this thread](https://forum.depmap.org/t/how-to-download-the-data-with-wget-or-curl/1642). Let me know if that answers your question.

Thanks,
Simone
