### ISSUE TITLE
What is the pseudo normal used to call mutations in cell lines?

### ISSUE THREAD

**Issue by ytakemon** [broadinstitute/depmap_omics#24]
Hello,

I'm trying to process WGS data from a cell line similar to how your pipeline at DepMap. I noticed in your [workflow doc](https://docs.google.com/presentation/d/1i0HI31dBejTYmzI9Cp6Ij7--t6eSR2r9vcC22TxSnNI/edit#slide=id.g51d9a1fac6_0_223) there was a note under the mutations slide that "this pipeline requires a matched normal, so we use a pseudo normal for all cell lines samples". Could you explain what this pseudo normal is and would it be possible for you to share this data with me?

Thank you

**Comment by javadnoorb** [comment]
Hi, 

For our Agilent WES samples we use:
`gs://firecloud-tcga-open-access/tutorial/bams/C835.HCC1143_BL.4.bam`
I think this is publicly available.

For our ICE samples we use a germline blood from the CCLF project's samples:
`gs://fc-38a1a377-72c6-4e90-917f-e4bb709b8f2c/CCLF_RCRF1009-Normal-SM-F3R8L/seq_data_v2/CCLF_RCRF1009GL.bam`
I'm not sure if this is publicly available, but give it a shot and let me know. 

For WGS we use this GTEx sample:
`GTEX-111FC-0001-SM-6WBTJ`
I think you'd need dbGaP access for this one and get it through the GTEx project.

@jkobject feel free to chime in if I'm missing some information

**Comment by ytakemon** [comment]
Thanks for the quick response! 

While trying to figure it out on my own I actually duplicated my question on the DepMap community [forum](https://forum.depmap.org/t/panel-of-normal-data-for-variant-calling/576). Sorry about this. 
 
Now having re-read the Ghandi et al (2019) paper again, I see that a pseudo normal (ie panel-of-normal, PoNs) were created via 8,000 TCGA normal samples. Is that the same as the GTEx `GTEX-111FC-0001-SM-6WBTJ` you are referring to?

**Comment by javadnoorb** [comment]
Yes. I would recommend posting in the forum for future questions.

Psuedonormal is a single sample that we use as a 'normal' because our cell
lines don't have paired normal but our mutation caller needs it.

Panel of normals(pon) is what you're referring to according to Ghandi et
al. That's made from a larger set of normals. These require dbGaP access so
unfortunately we wouldn't be able to share them.

**Comment by ytakemon** [comment]
I see. Thank you for clarifying what the psuedo-normal is and where the PoNs originated.  For the PoN, are you able to share the sample IDs were and what were the criteria used to select them (besides that they were normal tissue)? I will see if I can request them from GTEx biobank.

**Comment by javadnoorb** [comment]
closing this as it can be followed [here](https://forum.depmap.org/t/panel-of-normal-data-for-variant-calling/576).
