### ISSUE TITLE
Can the segment file downloaded from DepMap be used to run ABSOLUTE and GISTIC2 directly?

### ISSUE THREAD

**Issue by lincj1994** [broadinstitute/depmap_omics#57]
HI. I have downloaded the segment file from depmap portal and the Segment_Mean column (relative copy ratio for that segment) seems somewhat different from the Seg_Mean column in the standard segment file. So I dont know if this segment file can be used to run ABSOLUTE and GISTIC2 directly.

**Comment by jkobject** [comment]
Hello, 

what is the standard segment file?
