### ISSUE TITLE
Capture kit used in WES samples

### ISSUE THREAD

**Issue by Desjerry** [broadinstitute/depmap_omics#59]
I want to firstly thank you all for the great work on the CCLE/DepMap database! 

And recently I am processing whole-exon-sequencing samples from the CCLE_PRJNA523380 project. I am looking for the capture kit and PoN that used for each of the WES samples:

•	I found the sample_for_pon.tsv  file containing 1668 lanes of records (says from GTEx on the GitHub page), can you let me know if these samples are also used for the CCLE WES CNV process? And can you let me know where I can directly download the PoN file that corresponds to CCLE WES data?

•	On the GitHub page, you said you are using Illumina ICE intervals and Agilent intervals for WES samples, I can only find a [wes_agilent_hg19_baits.interval_list](https://github.com/broadinstitute/depmap_omics/blob/master/data/wes_agilent_hg19_baits.interval_list), which is very different from any Agilent released capture kit bed file. Can you let me know what is the exact capture kit that has been used for exon capture for all the CCLE WES data?

**Comment by chapaith** [comment]
Hi there, Can I work on this issue?
