### ISSUE TITLE
Mutect2 clustered events correction

### ISSUE THREAD

**Issue by ImNotaGit** [broadinstitute/depmap_omics#63]
While examining the somatic mutation pipeline I noticed recent "debug" commits making corrections for Mutect2 clustered_events: [d901564](https://github.com/broadinstitute/depmap_omics/commit/d9015640adf2bc839f16a96adc20e516424934c7), [559daef](https://github.com/broadinstitute/depmap_omics/commit/559daeff98b1f3f0b21c58a9d2b3c30572aad72c). These seem to change clustered_events to PASS when there are <=2 non-germline mutations in a +/- 50 bp region around the site.

It happens that I have also been looking for a reasonable solution aiming to prevent some clustered_events from being filtered out, as it has been known that this filter sometimes removes potentially "real" somatic mutations (e.g. [this post](https://gatk.broadinstitute.org/hc/en-us/community/posts/360059271532-Mutect2-filter-somatic-mutations-as-multiallelic-and-clustered-events)). Therefore I am very curious what you find after applying the correction above -- does it help to improve performance (e.g. reducing false negatives w/o greatly increasing false positives)? Is this approach official yet -- will the next DepMap release adopt this correction for clustered_events?

**Comment by colganwi** [comment]
Yes, the purpose of this script is to correct the clustered_events issue mentioned in the post. With a +/- 50 bp region, it decreases the clustered_events false-negative rate by ~90%. The total number of somatic mutations is increased by ~10%, but many of these "false positives" have low depth and allele fraction so will be removed by downstream filters.

Ideally, we would like to find a correction that recreates the somatic calls from running Mutect2 in somatic-only mode, but this is the best we have been able to do. Please let us know if you figure out a better correction procedure.

This approach is not official yet, we are still working on generating Mutect2 calls for our cell lines. We will QC these calls internally and then release them when we are confident they are accurate.
