### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by Yuweiiii** [broadinstitute/depmap_omics#71]
Thank you for giving such a good way to download depmap database for those who have difficulty installing depmap from Bioconductor (like me). However, I still have some issues in installing from github...
It shows that:
> install_github("depmap_omics")
Error in parse_repo_spec(repo) : 
  Invalid git repo specification: 'depmap_omics'

May I ask is there any solutions to this issue? Thank you for any response in advance.

yuwei

**Comment by jkobject** [comment]
Hello Yuweiii, 

First please know that depmap_omics is not depmap but just the multi omics analysis part of it (you won't get anything related to the dependency data).

Also, you cannot install depmap_omics from R nor is depmap_omics written in R. Here you will find the pipeline to analyse cancer cell line's omics data from raw fastq files. you will need to look at our Readme for more information, and to use Terra.bio and python3.

Hope it helps,
Best,
