### ISSUE TITLE
CCLE_mutations.csv MAF GRCh37

### ISSUE THREAD

**Issue by BiotechPedro** [broadinstitute/depmap_omics#77]
Hello!

By any chance, is there a way to release the mutational profiling of CCLE as a .vcf file instead of .maf? Also, related with the same data, are you planning to align agains GRch38 instead of 37, like you did for example with transcriptome?

Thank you!

Pedro

**Comment by 5im1z** [comment]
Hi Pedro!

All the public data from the CCLE lines are hosted in this terra workspace: https://app.terra.bio/#workspaces/broad-firecloud-ccle/CCLE_v2/data. If you navigate to the sample data table, you can find location of the VCFs in columns mutect2_vcf_wes and mutect2_vcf_wgs. Note that these are stored in a requester-pays google bucket and you will have to provide a google cloud billing project when you download the data.

We updated our mutation calling pipeline in 22Q4 and started using Hg38 alignment for the mutation dataset, so both these VCFs and the MAF on the portal are in Hg38 now.

Best,
Simone

**Comment by BiotechPedro** [comment]
Hi Simone @5im1z 

It's great to have the alignment to hg38 in the 22Q4 release. However, I didn't find a way to relate the variants with the cell lines ID in the OmicsSomaticMutations.csv file. Am I missing something?

Thanks!

Pedro
