### ISSUE TITLE
Revert OmicsSomaticMutations.csv to MAF and validate the MAF columns 

### ISSUE THREAD

**Issue by 5im1z** [broadinstitute/depmap_omics#87]
Currently some boolean columns are populated with either "Y" or NaNs. Need to convert them to True/False

**Comment by qinqian** [comment]
1. convert bool columns in MAF to True/False.
2. be compatible with the [reference](https://docs.gdc.cancer.gov/Data/File_Formats/MAF_Format/).
3. validate columns using [pandera](https://pandera.readthedocs.io/en/stable/index.html)
